import fs from 'fs';
import path from 'path';

export const updateModelIndex = () => {
    const rootDir = process.cwd();
    const modelsDir = path.join(rootDir, 'src', 'app', '(backend)', 'models');
    const indexPath = path.join(rootDir, 'src', 'app', 'utils', 'db', 'allModels.js');

    const getAllFiles = (dirPath, arrayOfFiles) => {
        const files = fs.readdirSync(dirPath);

        arrayOfFiles = arrayOfFiles || [];

        files.forEach((file) => {
            if (fs.statSync(path.join(dirPath, file)).isDirectory()) {
                arrayOfFiles = getAllFiles(path.join(dirPath, file), arrayOfFiles);
            } else {
                if (file.endsWith('.modal.js')) {
                    arrayOfFiles.push(path.join(dirPath, file));
                }
            }
        });

        return arrayOfFiles;
    };

    try {
        if (!fs.existsSync(modelsDir)) return;

        const modelFiles = getAllFiles(modelsDir);
        const importLines = modelFiles.map(file => {
            // Convert absolute path to alias path (@/app/...)
            const relativeToApp = path.relative(path.join(rootDir, 'src', 'app'), file).replace(/\\/g, '/');
            return `import "@/app/${relativeToApp}";`;
        });

        const content = `// This file is auto-generated by ModuleGenerator.js\n// Do not edit this file manually.\n\n${importLines.join('\n')}\n`;

        fs.writeFileSync(indexPath, content);
        console.log(`✅ Updated Model Index at ${indexPath}`);
    } catch (error) {
        console.error('❌ Error updating model index:', error);
    }
};
