// This file is auto-generated by ModuleGenerator.js
// Do not edit this file manually.

import "@/app/(backend)/models/administrator/RBAC/RBAC.modal.js";
import "@/app/(backend)/models/cms/(media)/blog/blog.modal.js";
import "@/app/(backend)/models/cms/(media)/blog-tag/blog-tag.modal.js";
import "@/app/(backend)/models/cms/(media)/corporate-responsibility/corporate-responsibility.modal.js";
import "@/app/(backend)/models/cms/(media)/news/news.modal.js";
import "@/app/(backend)/models/cms/(miscellaneous)/footer/footer.modal.js";
import "@/app/(backend)/models/cms/(miscellaneous)/header/header.modal.js";
import "@/app/(backend)/models/cms/(pages)/about-us-page/about-us-page.modal.js";
import "@/app/(backend)/models/cms/(pages)/common-page/common-page.modal.js";
import "@/app/(backend)/models/cms/(pages)/contact-us-page/contact-us-page.modal.js";
import "@/app/(backend)/models/cms/(pages)/csr-page/csr-page.modal.js";
import "@/app/(backend)/models/cms/(pages)/home-page/home-page.modal.js";
import "@/app/(backend)/models/cms/(pages)/vigro-gold-club-page/vigro-gold-club-page.modal.js";
import "@/app/(backend)/models/cms/(sections)/managing-directors/managing-directors.modal.js";
import "@/app/(backend)/models/cms/banner/banner.modal.js";
import "@/app/(backend)/models/cms/certifications/certifications.modal.js";
import "@/app/(backend)/models/cms/event/event.modal.js";
import "@/app/(backend)/models/cms/jobs-opening/jobs-opening.modal.js";
import "@/app/(backend)/models/cms/policies/policies.modal.js";
import "@/app/(backend)/models/cms/testimonies/testimonies.modal.js";
import "@/app/(backend)/models/leads/career-enquire/career-enquire.modal.js";
import "@/app/(backend)/models/leads/enquire-now/enquire-now.modal.js";
import "@/app/(backend)/models/setting/page-component/page-component.modal.js";
import "@/app/(backend)/models/setting/pages-conf/pages-conf.modal.js";
import "@/app/(backend)/models/shop/brand-catalogue/brand-catalogue.modal.js";
import "@/app/(backend)/models/shop/brands/brands.modal.js";
import "@/app/(backend)/models/shop/category/category.modal.js";
import "@/app/(backend)/models/shop/products/products.modal.js";
