export const default_SEO = {
    title: "Admin Panel Audio & Image LLP",
    description: "",
    keywords: "",
    image: `${process.env.NEXT_PUBLIC_SITE_URL}/images/admin/logo.webp`, // og image
    logo: `${process.env.NEXT_PUBLIC_SITE_URL}/images/admin/logo.webp` // twitter defualt image
}

export const SEO_SECTION = {
    "Heading": "Seo",
    "fields": [
        {
            "type": "component",
            "field": "seo",
            "Printvalue": "seo",
            "colSpace": "col-6",
            "required": false,
            "disable_in_edit": false,
            "showInTable": false,
            "sort": 2,
            "placeholder": null,
            "FieldPurpose": null,
            "component_key": "seo",
            "component_display_name": "seo",
            "component_icon": "puzzle",
            "component_type": "single",
            "component_creation_mode": true,
            "fields": [
                {
                    "field": {
                        "label": "title",
                        "value": "title"
                    },
                    "Printvalue": "Meta Title",
                    "type": "rich-text-blocks",
                    "colSpace": "col-6",
                    "required": true,
                    "disable_in_edit": false,
                    "showInTable": false,
                    "sort": 0,
                    "placeholder": null,
                    "FieldPurpose": "A 50-60 character tag that defines the page’s title for search engines and browsers. It should include relevant keywords and be unique and compelling.",
                    "unique": false,
                    "index": false,
                    "sparse": false,
                    "default_value": null,
                    "match_regex": null,
                    "trim": false,
                    "lowercase": false,
                    "uppercase": false,
                    "dependency_field": null,
                    "dependency_field_target": null,
                    "dependency_action": "show"
                },
                {
                    "field": {
                        "label": "description",
                        "value": "description"
                    },
                    "Printvalue": "Meta Description",
                    "type": "rich-text-blocks",
                    "colSpace": "col-6",
                    "required": true,
                    "disable_in_edit": false,
                    "showInTable": false,
                    "sort": 1,
                    "placeholder": null,
                    "FieldPurpose": "A 150-160 character summary of the page content. It doesn’t impact rankings but influences click-through rates by attracting users to click on search results.",
                    "unique": false,
                    "index": false,
                    "sparse": false,
                    "default_value": null,
                    "match_regex": null,
                    "trim": false,
                    "lowercase": false,
                    "uppercase": false,
                    "dependency_field": null,
                    "dependency_field_target": null,
                    "dependency_action": "show"
                },
                {
                    "field": {
                        "label": "keywords",
                        "value": "keywords"
                    },
                    "Printvalue": "Meta Keywords",
                    "type": "rich-text-blocks",
                    "colSpace": "col-6",
                    "required": false,
                    "disable_in_edit": false,
                    "showInTable": false,
                    "sort": 2,
                    "placeholder": null,
                    "FieldPurpose": "An outdated tag where relevant keywords were listed. Modern SEO largely ignores this field, so its optional and should not be overused.",
                    "unique": false,
                    "index": false,
                    "sparse": false,
                    "default_value": null,
                    "match_regex": null,
                    "trim": false,
                    "lowercase": false,
                    "uppercase": false,
                    "dependency_field": null,
                    "dependency_field_target": null,
                    "dependency_action": "show"
                },
                {
                    "field": {
                        "label": "metaImage",
                        "value": "metaImage"
                    },
                    "Printvalue": "Image",
                    "type": "media",
                    "colSpace": "col-6",
                    "required": false,
                    "disable_in_edit": false,
                    "showInTable": false,
                    "sort": 3,
                    "placeholder": null,
                    "FieldPurpose": "A social media-specific tag that defines the image shown when sharing links on platforms like Facebook. It enhances engagement by providing a visual preview.",
                    "unique": false,
                    "index": false,
                    "sparse": false,
                    "default_value": null,
                    "match_regex": null,
                    "trim": false,
                    "lowercase": false,
                    "uppercase": false,
                    "dependency_field": null,
                    "dependency_field_target": null,
                    "dependency_action": "show",
                    "accept_type": "image/*",
                    "fileLimit": "5"
                },
                {
                    "type": "component",
                    "field": {
                        "label": "openGraph",
                        "value": "openGraph"
                    },
                    "Printvalue": "openGraph",
                    "colSpace": "col-6",
                    "required": false,
                    "disable_in_edit": false,
                    "showInTable": false,
                    "sort": 4,
                    "placeholder": null,
                    "FieldPurpose": null,
                    "component_key": "openGraph",
                    "component_display_name": "Open Graph",
                    "component_icon": "puzzle",
                    "component_type": "repeatable",
                    "component_creation_mode": true,
                    "fields": [
                        {
                            "field": {
                                "label": "ogTitle",
                                "value": "ogTitle"
                            },
                            "Printvalue": "OG Title",
                            "type": "rich-text-blocks",
                            "colSpace": "col-6",
                            "required": false,
                            "disable_in_edit": false,
                            "showInTable": false,
                            "sort": 0,
                            "placeholder": null,
                            "FieldPurpose": "Defines the title shown when the page is shared on social media platforms. It may differ from the page title to improve engagement and click-through rates.",
                            "unique": false,
                            "index": false,
                            "sparse": false,
                            "default_value": null,
                            "match_regex": null,
                            "trim": false,
                            "lowercase": false,
                            "uppercase": false,
                            "dependency_field": null,
                            "dependency_field_target": null,
                            "dependency_action": "show"
                        },
                        {
                            "field": {
                                "label": "ogDescription",
                                "value": "ogDescription"
                            },
                            "Printvalue": "OG Description",
                            "type": "rich-text-blocks",
                            "colSpace": "col-6",
                            "required": false,
                            "disable_in_edit": false,
                            "showInTable": false,
                            "sort": 1,
                            "placeholder": null,
                            "FieldPurpose": "Specifies the summary text displayed in social media link previews. It should be concise, engaging, and optimized to encourage clicks.",
                            "unique": false,
                            "index": false,
                            "sparse": false,
                            "default_value": null,
                            "match_regex": null,
                            "trim": false,
                            "lowercase": false,
                            "uppercase": false,
                            "dependency_field": null,
                            "dependency_field_target": null,
                            "dependency_action": "show"
                        },
                        {
                            "field": {
                                "label": "ogImage",
                                "value": "ogImage"
                            },
                            "Printvalue": "OG Image",
                            "type": "media",
                            "colSpace": "col-6",
                            "required": false,
                            "disable_in_edit": false,
                            "showInTable": false,
                            "sort": 2,
                            "placeholder": null,
                            "FieldPurpose": null,
                            "unique": false,
                            "index": false,
                            "sparse": false,
                            "default_value": null,
                            "match_regex": null,
                            "trim": false,
                            "lowercase": false,
                            "uppercase": false,
                            "dependency_field": null,
                            "dependency_field_target": null,
                            "dependency_action": "show",
                            "accept_type": "image/*",
                            "fileLimit": "5"
                        },
                        {
                            "field": {
                                "label": "ogUrl",
                                "value": "ogUrl"
                            },
                            "Printvalue": "ogUrl",
                            "type": "text",
                            "colSpace": "col-6",
                            "required": false,
                            "disable_in_edit": false,
                            "showInTable": false,
                            "sort": 3,
                            "placeholder": null,
                            "FieldPurpose": "The official URL used in social media link previews to ensure consistent sharing and accurate engagement tracking.",
                            "unique": false,
                            "index": false,
                            "sparse": false,
                            "default_value": null,
                            "match_regex": null,
                            "trim": false,
                            "lowercase": false,
                            "uppercase": false,
                            "dependency_field": null,
                            "dependency_field_target": null,
                            "dependency_action": "show"
                        },
                        {
                            "field": {
                                "label": "ogType",
                                "value": "ogType"
                            },
                            "Printvalue": "ogType",
                            "type": "text",
                            "colSpace": "col-6",
                            "required": false,
                            "disable_in_edit": false,
                            "showInTable": false,
                            "sort": 4,
                            "placeholder": null,
                            "FieldPurpose": "Defines the type of content being shared in Open Graph metadata (e.g., website, article, product, video). It helps social media platforms understand how to categorize and display the content when shared.",
                            "unique": false,
                            "index": false,
                            "sparse": false,
                            "default_value": null,
                            "match_regex": null,
                            "trim": false,
                            "lowercase": false,
                            "uppercase": false,
                            "dependency_field": null,
                            "dependency_field_target": null,
                            "dependency_action": "show"
                        }
                    ]
                },
                {
                    "field": {
                        "label": "canonicalUrl",
                        "value": "canonicalUrl"
                    },
                    "Printvalue": "Canonical Url",
                    "type": "text",
                    "colSpace": "col-12",
                    "required": false,
                    "disable_in_edit": false,
                    "showInTable": false,
                    "sort": 5,
                    "placeholder": null,
                    "FieldPurpose": "Specifies the preferred URL of the page to prevent duplicate content issues and improve SEO ranking.",
                    "unique": false,
                    "index": false,
                    "sparse": false,
                    "default_value": null,
                    "match_regex": null,
                    "trim": false,
                    "lowercase": false,
                    "uppercase": false,
                    "dependency_field": null,
                    "dependency_field_target": null,
                    "dependency_action": "show"
                },
                {
                    "field": {
                        "label": "schemaMarkup",
                        "value": "schemaMarkup"
                    },
                    "Printvalue": "Schema markup ",
                    "type": "json",
                    "colSpace": "col-12",
                    "required": false,
                    "disable_in_edit": false,
                    "showInTable": false,
                    "sort": 6,
                    "placeholder": null,
                    "FieldPurpose": "A structured data field used to define Schema.org markup in JSON-LD format. This improves search engine visibility and allows the page to qualify for enhanced search features like rich snippets and knowledge panels.",
                    "unique": false,
                    "index": false,
                    "sparse": false,
                    "default_value": null,
                    "match_regex": null,
                    "trim": false,
                    "lowercase": false,
                    "uppercase": false,
                    "dependency_field": null,
                    "dependency_field_target": null,
                    "dependency_action": "show"
                }
            ]
        }
    ],
}